/**
 * Generates `packages/theme/src/tokens.generated.css` from the canonical tokens.
 * Keeps Tailwind's `@theme` in sync with `tokens.ts` — one source, no hand-mirroring.
 *
 * Run: `bun run tools/gen-theme/index.ts` (wired into the web build prestep).
 */
import { writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { themeVars } from '../../packages/theme/src/tokens'

const out = join(import.meta.dir, '../../packages/theme/src/tokens.generated.css')

const body = Object.entries(themeVars)
  .map(([k, v]) => `  ${k}: ${v};`)
  .join('\n')

const css = `/* AUTO-GENERATED by tools/gen-theme — do not edit. Source: packages/theme/src/tokens.ts */
@theme {
${body}
}
`

writeFileSync(out, css)
console.log(`gen-theme: wrote ${Object.keys(themeVars).length} vars → ${out}`)
