/**
 * Generates `packages/theme/src/tokens.generated.css` from the canonical tokens.
 * Light is the `@theme` default; dark overrides the colour vars under [data-theme='dark'].
 * One source (tokens.ts), no hand-mirroring. Build prestep.
 */
import { writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { colorVars, palettes, staticVars } from '../../packages/theme/src/tokens'

const out = join(import.meta.dir, '../../packages/theme/src/tokens.generated.css')

const block = (vars: Record<string, string>) =>
  Object.entries(vars)
    .map(([k, v]) => `  ${k}: ${v};`)
    .join('\n')

const css = `/* AUTO-GENERATED by tools/gen-theme — do not edit. Source: packages/theme/src/tokens.ts */
@theme {
${block({ ...colorVars(palettes.light), ...staticVars })}
}

[data-theme='dark'] {
${block(colorVars(palettes.dark))}
}
`

writeFileSync(out, css)
console.log(`gen-theme: wrote light + dark themes → ${out}`)
