import { role } from '@noahclark/schema'

/**
 * Roles, chronological. Copy is grounded in the résumé (epistemic-mode: no hype,
 * metrics traceable). `kind` drives the node's shape/colour in the graph.
 */
export const roles = [
  role({
    id: 'usaf-analyst',
    kind: 'military',
    org: 'org-usaf',
    title: 'Intelligence Analyst / Physical Security Penetration Tester',
    start: '2007-09',
    end: '2011-07',
    summary:
      'Cyber intelligence analyst and physical security penetration tester. My job was to find the holes in the Air Force’s security posture and brief personnel on cyber threats.',
    threads: ['intelligence'],
  }),
  role({
    id: 'questor',
    kind: 'employment',
    org: 'org-questor',
    title: 'Technology Consultant',
    start: '2011-07',
    end: '2013-05',
    location: { label: 'Washington, DC', lat: 38.9072, lng: -77.0369 },
    summary:
      'Consulted on IT consolidation across the US Intelligence Community, drawing up roadmaps with senior leadership to cut a duplicative IT footprint.',
    threads: ['intelligence'],
  }),
  role({
    id: 'dia-architect',
    kind: 'employment',
    org: 'org-thermopylae',
    title: 'Senior Systems Architect / Senior Software Engineer',
    start: '2013-05',
    end: '2015-08',
    location: { label: 'Washington, DC', lat: 38.9072, lng: -77.0369 },
    summary:
      'At DMI / Thermopylae, I set the strategy for consolidating the Defense Intelligence Agency’s IT infrastructure onto centralised cloud, and was the architect and lead engineer on the DIA’s IT asset management system.',
    highlights: [
      'Wrote the strategy and execution plan for consolidating a $1.1B IT infrastructure onto centralised cloud',
      'Architected and led development of the DIA’s IT asset management system',
      'Modelled assets as a graph (Neo4j, d3.js, cytoscape.js): the first knowledge-graph system in a 13-year through-line',
    ],
    metrics: [{ label: 'IT infrastructure scope', value: '$1.1B' }],
    threads: ['intelligence', 'graph'],
    projects: ['dia-asset-mgmt'],
    skills: ['openstack', 'angular', 'php', 'neo4j', 'd3', 'cytoscape'],
  }),
  role({
    id: 'cmu',
    kind: 'research',
    org: 'org-cmu',
    title: 'Software Developer',
    start: '2016-05',
    end: '2017-05',
    location: { label: 'Pittsburgh, PA', lat: 40.4406, lng: -79.9959 },
    summary:
      'I worked with the principal investigator of a neuroscience lab, building an automated MATLAB pipeline to normalise and analyse fMRI data. The start of a decade at the boundary of software and first-person experience.',
    highlights: ['Built an automated MATLAB pipeline to normalise and analyse fMRI data'],
    threads: ['consciousness'],
    projects: ['fmri-pipeline'],
    skills: ['matlab'],
  }),
  role({
    id: 'thermopylae-geo',
    kind: 'employment',
    org: 'org-thermopylae',
    title: 'Geospatial Analyst / Software Engineer',
    start: '2018-11',
    end: '2020-01',
    location: { label: 'Arlington, VA', lat: 38.8816, lng: -77.091 },
    summary:
      'I supported global commercial imagery collection and automated the pipeline behind it.',
    highlights: [
      'Automated imagery compression/decompression in Node.js, removing ~400 hours of manual labour',
    ],
    metrics: [{ label: 'Manual labour removed', value: '~400 hrs' }],
    threads: ['intelligence'],
    projects: ['imagery-pipeline'],
    skills: ['javascript'],
  }),
  role({
    id: 'ga-instructor',
    kind: 'instruction',
    org: 'org-ga',
    title: 'Instructor Team Lead / Full-Stack Engineer',
    start: '2020-01',
    end: '2020-12',
    location: { label: 'Washington, DC', lat: 38.9072, lng: -77.0369 },
    summary:
      'I taught and maintained the 500-hour full-stack engineering immersive, and built internal tooling, including a learning platform structured as a hierarchical knowledge graph.',
    highlights: [
      'Taught the full-stack immersive: Git, HTML/CSS/JS, Python, React, Mongo, PostgreSQL, Django, Node/Express',
      'Built an automated grading application in Node.js for the DC campus',
      'Built a spaced-repetition learning platform on a hierarchical knowledge-graph data structure (Neo4j, Node, Express, React)',
    ],
    threads: ['graph'],
    projects: ['ga-grading-app', 'ga-learning-platform'],
    skills: ['react', 'javascript', 'python', 'neo4j', 'postgresql', 'mongodb'],
  }),
  role({
    id: 'nderf',
    kind: 'employment',
    org: 'org-nderf',
    title: 'Full-Stack Engineer / Data Manager',
    start: '2020-01',
    end: '2021-05',
    location: { label: 'Houma, LA', lat: 29.5958, lng: -90.7195 },
    summary:
      'I designed the system architecture and a prototype API platform for the Near Death Experience Research Foundation’s data and collection workflow.',
    threads: ['consciousness'],
    projects: ['nderf-platform'],
    skills: ['javascript', 'postgresql', 'react', 'heroku'],
  }),
  role({
    id: 'sei',
    kind: 'employment',
    org: 'org-sei',
    title: 'Engineering Manager / Senior Full-Stack Engineer',
    start: '2021-05',
    end: '2023-09',
    location: { label: 'Herndon, VA', lat: 38.9696, lng: -77.3861 },
    summary:
      'Engineering manager and platform subject-matter expert for an EdTech SaaS startup. I owned the architecture and ran the team while the product grew from a few hundred users to over a million.',
    highlights: [
      'Scaled the platform from a few hundred users and two clients to 1.2M+ users and 59 corporate partners',
      'Managed four engineers and three QA specialists',
      'Owned platform architecture, CI/CD pipelines, and code-review standards',
    ],
    metrics: [
      { label: 'Users', value: '1.2M+' },
      { label: 'Corporate partners', value: '59' },
      { label: 'Team', value: '7 (4 eng + 3 QA)' },
    ],
    threads: ['scale'],
    projects: ['workforceedge'],
    skills: ['typescript', 'apollo', 'graphql', 'postgresql', 'redis', 'react', 'aws', 'ci-cd'],
  }),
  role({
    id: 'iam-founder',
    kind: 'founding',
    org: 'org-iam',
    title: 'Sole Developer',
    start: '2023-09',
    end: 'present',
    location: { label: 'Amsterdam, NL', lat: 52.3676, lng: 4.9041 },
    summary:
      'I built and run iAm, a platform for measuring and analysing subjective experience in real time. Designed and shipped the whole stack solo: a graph-native data framework that unifies surveys and real-time reporting, delivered cross-platform.',
    highlights: [
      'Designed a flexible graph-based data framework on Neo4j for first-person experience data',
      'Developed a methodology for real-time subjective-experience measurement',
      'Built and deployed the full platform solo (Neo4j, TypeScript, Node, Apollo, GraphQL, React, GCP/GKE)',
      'Shipped cross-platform to iOS and Android with Capacitor',
    ],
    threads: ['consciousness', 'graph', 'ai-native'],
    projects: ['iam'],
    skills: ['neo4j', 'typescript', 'apollo', 'graphql', 'react', 'capacitor', 'gcp', 'kubernetes', 'aws'],
  }),
  role({
    id: 'quatt',
    kind: 'employment',
    org: 'org-quatt',
    title: 'Cloud Team Lead',
    start: '2024-11',
    end: 'present',
    location: { label: 'Amsterdam, NL', lat: 52.3676, lng: 4.9041 },
    summary:
      'Lead the team building the cloud platform behind a fleet of 20,000+ IoT-connected heat pumps, from device telemetry ingestion through real-time processing, APIs, dashboards, and analytics. Work daily across firmware, backend, mobile, and data boundaries.',
    highlights: [
      'Own the real-time telemetry pipeline (MQTT, AWS IoT Core, SQS) for 20,000+ distributed devices',
      'Redesigned the fleet-management dashboard: remote diagnostics, live telemetry, device control',
      'Shipped 3 hardware products end-to-end: protocol design through commissioning, APIs, dashboards',
      'Created Atlas, a typed knowledge-graph modelling 670 entities, 41 repos, and 600+ device fields with cross-language type generation',
      'Built AI-assisted code-review and debugging tooling (Claude Code, MCP); managed 20+ releases',
    ],
    metrics: [
      { label: 'IoT devices', value: '20,000+' },
      { label: 'Engineers led', value: '5' },
      { label: 'Atlas entities', value: '670' },
      { label: 'Releases', value: '20+' },
    ],
    threads: ['scale', 'ai-native', 'graph'],
    projects: ['atlas', 'quatt-cloud'],
    skills: ['typescript', 'mqtt', 'aws', 'clickhouse', 'mysql', 'redis', 'kafka', 'nx', 'claude-code', 'mcp', 'openapi', 'asyncapi'],
  }),
  role({
    id: 'open-volunteer',
    kind: 'volunteer',
    org: 'org-open',
    title: 'Volunteer Engineer',
    // start month is an estimate; correct if needed.
    start: '2023-09',
    end: 'present',
    location: { label: 'Amsterdam, NL', lat: 52.3676, lng: 4.9041 },
    summary:
      'Volunteer web and engineering work for OPEN Foundation, the non-profit behind the ICPR conference.',
    highlights: [
      'Built the ICPR 2024 conference website',
    ],
    threads: ['consciousness'],
    projects: ['icpr-conference'],
    skills: ['nextjs', 'react', 'typescript'],
  }),
]
